"""Tests for the generated-Makefile integrity stamp.

The stamp is what lets `eda-buddy build/run` auto-regenerate a stale Makefile
without silently destroying hand-edits, so its failure modes matter more than
its success case. Run standalone:

    python tests/test_checksum.py
"""

import os
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

from eda_buddy.makefile_gen import (  # noqa: E402
    compute_checksum, is_pristine, read_checksum, strip_checksum,
)

def _write(tmp, text):
    path = os.path.join(tmp, "Makefile")
    with open(path, "w") as f:
        f.write(text)
    return path


def _make_stamped():
    """Build a correctly stamped Makefile the same way generate() does."""
    body = "## AUTO-GENERATED BY EDA BUDDY\nROOT := /tmp/run\nall:\n\t@echo hi"
    stamp = "## eda-buddy-checksum: sha256:{}".format(compute_checksum(body))
    return body.replace("\n", "\n{}\n".format(stamp), 1)


def test_strip_and_read():
    text = _make_stamped()
    assert read_checksum(text) is not None, "stamp should be readable"
    assert "eda-buddy-checksum" not in strip_checksum(text), "strip should remove the stamp"


def test_pristine_file_is_recognized():
    tmp = tempfile.mkdtemp()
    path = _write(tmp, _make_stamped())
    assert is_pristine(path), "freshly generated Makefile must read as pristine"


def test_hand_edit_is_detected():
    tmp = tempfile.mkdtemp()
    text = _make_stamped().replace("ROOT := /tmp/run", "ROOT := /somewhere/else")
    path = _write(tmp, text)
    assert not is_pristine(path), "edited ROOT must invalidate the stamp"


def test_unstamped_file_is_not_pristine():
    """A Makefile from before checksums existed has unknown provenance and must
    be treated as hand-edited, so auto-regen preserves a copy."""
    tmp = tempfile.mkdtemp()
    path = _write(tmp, "## AUTO-GENERATED BY EDA BUDDY\nROOT := /tmp/run\n")
    assert not is_pristine(path)


def test_missing_file_is_not_pristine():
    assert not is_pristine(os.path.join(tempfile.mkdtemp(), "nope"))


def test_editing_only_the_stamp_is_detected():
    tmp = tempfile.mkdtemp()
    text = _make_stamped().replace("sha256:", "sha256:0")
    path = _write(tmp, text)
    assert not is_pristine(path)


if __name__ == "__main__":
    failures = []
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print("  ok   {}".format(name))
            except AssertionError as e:
                failures.append("{}: {}".format(name, e))
                print("  FAIL {}".format(name))
    if failures:
        print("\n".join(failures))
        sys.exit(1)
    print("PASS - checksum behavior verified")
